### PR TITLE
Fix Xcode 11 Bug with New Build System and Update to Swift 5

### PR DESCRIPTION
**Pull request by narlei**
- I fixed the bundle and how it get images from bundle.
- Updated to Swift 5;
- Update to version 0.1.5 in podspac

### CODE REVIEW

**Comment by VickyPrajapati24** [comment]
can you please release new version with above changes to resolve unexpected duplicate tasks. #9 . I don't know how to get latest code from this commit release. Please provide latest pod version.

**Comment by barotbhavesh** [comment]
Please replace your pod file name 
pod 'IHProgressHUD' 
to
pod 'IHProgressHUD', :git => 'https://github.com/Swiftify-Corp/IHProgressHUD.git'

**Comment by VickyPrajapati24** [comment]
Screenshot 2020-01-21 at 10 50 54 AM

It his pos gives errors

**Comment by barotbhavesh** [comment]
your project support swift 5?
if yes then IHprogressHud uninstall in your pod then close Xcode then reopen and then install again with 
pod 'IHProgressHUD', :git => 'https://github.com/Swiftify-Corp/IHProgressHUD.git'
then again close Xcode clean derived Data now open Xcode and use **Command + shift + K** now run project.

**Pull request merged**
